apiVersion: apps/v1
kind: Deployment
metadata:
  name: todos-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      run: backend
  template:
    metadata:
      labels:
        run: backend
    spec:
      containers:
        - name: todos-backend-container
          image: todos-backend
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
              hostPort: 8000
