# yaml-language-server: $schema=file://home/psacawa/.kube/schema/v1.18.1-standalone-strict/service.json
apiVersion: v1
kind: Service
metadata:
  name: todos-backend-service
spec:
  type: NodePort
  selector:
    run: backend
  ports:
    - name: http
      targetPort: 8000
      port: 8080
