apiVersion: v1
kind: Service
metadata:
  name: todos-backend-service
  labels:
    app: todos
    component: backend
spec:
  selector:
    app: todos
    component: backend
  ports:
    - name: backend-http
      port: 8000
