apiVersion: v1
kind: Service
metadata:
  name: todos-frontend-service
  labels:
    app: todos
    component: frontend
spec:
  selector:
    app: todos
    component: frontend
  ports:
    - name: frontend-http
      port: 80
