on:
  push:
    branches:
      - "master"
  workflow_dispatch:

jobs:
  build-containers:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        context: [frontend, backend]
    steps:
      - uses: actions/checkout@v1
      - run: docker build --tag todos-${{ matrix.context }}-image backend
      - name: Login to ECR
        uses: docker/login-action@v1
        with:
          registry: 886185890074.dkr.ecr.us-east-2.amazonaws.com
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.context }}
          push: true
          tags: todos-${{ matrix.context }}-image
