on:
  push:
    branches:
      - "master"
  workflow_dispatch:

jobs:
  build-containers:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        context: [frontend, backend]
    steps:
      - uses: actions/checkout@v1
      - run: docker build --tag todos-${{ matrix.context }}-image ${{ matrix.context }}
      - name: Push backend to ECR
        id: build-backend
        uses: jwalton/gh-ecr-push@v1
        with:
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: us-east-2
          image: todos-${{ matrix.context }}-image
