on:
  push:
    branches:
      - "master"
  workflow_dispatch:

jobs:
  build-containers:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        image: [frontend, backend]
    steps:
      - uses: actions/checkout@v1
      - run: docker build --tag todos-${{ matix.image }}-image backend
      - name: Push ${{ matix.image }} to ECR
        id: build-${{ matix.image }}
        uses: jwalton/gh-ecr-push@v1
        with:
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: us-east-2
          image: todos-${{ matix.image }}-image
